apiVersion: v1
kind: Secret                            # Define resource Secret untuk menyimpan data sensitif seperti username & password
metadata:
  name: mongo-secret                    # Nama Secret yang akan direferensikan oleh Pod/Deployment
  namespace: karsajobs-ns               # Secret ini berada pada namespace karsajobs-ns
type: Opaque                            # Tipe default untuk menyimpan data dalam format key-value (base64 encoded)
data:
  MONGO_ROOT_USERNAME: YWRtaW4=         # Nilai 'admin' dalam base64
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==  # Nilai 'supersecretpassword' dalam base64
