# Service ClusterIP untuk shipping-service
apiVersion: v1                  
kind: Service                   # mendifinisikan kubernetes object "service"
metadata:
  name: shipping-service-svc    # nama service yang akan dibuat
  namespace: e-commerce         # namespace tempat service ini berada
spec:                           # mendefinisikan spesifikasi apa saja yang akan digunakan
  selector:                     # label selector untuk mencocokkan pod yang akan dilayani oleh service
    app: shipping-service       # pod yang memiliki label 'app: shipping-service' akan dipilih 
  type: NodePort
  ports:
    - name: http  
      protocol: TCP             # protokol yang digunakan (TCP)
      port: 3001                # port yang diekspos oleh service di dalam cluste
      targetPort: 3001          # port pada Pod yang menjadi tujuan trafik
